#!/bin/bash

# Dependencies:
# - imagemagick
# - xclip

# Default image format
DEFAULT_FORMAT="png"

# Default sub-directory of images folder
DEFAULT_DIRECTORY="shot"

# Size of image view in percentage of screen
VIEW_SIZE=60

# Image formats
FORMATS=(png jpg gif bmp tif)

# Show image instead of screenshot icon in notifications
IMAGE_IN_NOTIFICATION=true

# Default command line argument values
source="fullscreen"
destination="file"
view_image=false
delay="0"

show_help() {

    echo "Usage: screenshot [OPTIONS] [PATH]"
    echo
    echo "Content:"
    echo "  -f, --fullscreen     Grab full screen (default)"
    echo "  -w, --window         Grab active window"
    echo "  -s, --selection      Grab a selection"
    echo
    echo "Options:"
    echo "  -c, --clipboard      Send screenshot to clipboard"
    echo "  -d, --delay SECONDS  Delay before screenshot"
    echo "  -v, --view           View Screenshot"
    echo "  -h, --help           Show this message"

    exit 0

}

base_directory() {

    if [ -n "$XDG_CONFIG_HOME" ]; then
        config_dir=$XDG_CONFIG_HOME
    else
        config_dir="$HOME/.config"
    fi

    user_dirs_path="$config_dir/user-dirs.dirs"

    if [ -f "$user_dirs_path" ]; then

        dir="$(eval echo $(cat $user_dirs_path | grep XDG_PICTURES_DIR | cut -d '=' -f2 | tr -d \"))"

        if [ -d "$dir" ]; then
            base_dir=$dir
        fi

    fi

    if [ -z "$base_dir" ]; then

        dirs=(Pictures pictures Images images)

        for dir in ${dirs[@]}; do
            if [ -d "$HOME/$dir" ]; then
                base_dir="$HOME/$dir"
                break
            fi
        done

    fi

    if [ -z "$base_dir" ]; then
        base_dir=$HOME
    fi

    echo $base_dir

}

while [ "$1" != "" ]; do
    case "$1" in
        '-h'|'--help')
            show_help
            ;;
        '-s'|'--selection')
            source="selection"
            shift 1
            ;;
        '-w'|'--window')
            source="window"
            shift 1
            ;;
        '-f'|'--fullscreen')
            source="fullscreen"
            shift 1
            ;;
        '-c'|'--clipboard')
            destination="clipboard"
            shift 1
            ;;
        '-v'|'--view')
            view_image=true
            shift 1
            ;;
        '-d'|'--delay')
            delay=$2
            shift 2
            ;;
        *)
            arg=$1
            if [ "${arg:0:1}" != "-" ] && [[ " ${arg[@]} " =~ "." ]]; then
                path=$arg
                shift 1
            else
                echo "Invalid argument: $1"
                exit 1
            fi
            ;;
    esac
done

# Set path if necessary
if [ "$destination" == "clipboard" ]; then

    if [ -n "$XDG_CACHE_HOME" ]; then
        directory=$XDG_CACHE_HOME
    else
        directory="$HOME/.cache"
    fi

    filename="screenshot.$DEFAULT_FORMAT"
    path="$directory/$filename"

elif [ -z "$path" ]; then

    filename="$(date "+%Y-%m-%d_%H:%M:%S").$DEFAULT_FORMAT"
    path="$(base_directory)/$DEFAULT_DIRECTORY/$filename"

    # If path already exists then add milliseconds to filename
    if [ -f "$path" ]; then
        filename="$(date "+%Y-%m-%d_%H:%M:%S.%N").$DEFAULT_FORMAT"
        path="$(base_directory)/$DEFAULT_DIRECTORY/$filename"
    fi

fi

if [ -z "$filename" ]; then
    filename="$(basename $path)"
fi

# if path is not absolute then set path to "$PWD/$path"
if [ "${str:0:1}" != "/" ]; then
    path="$PWD/$path"
fi

# Validate image format
format=$(echo $path | awk -F '.' '{print $NF}')

if ! [[ " ${FORMATS[@]} " =~ " ${format} " ]]; then
    echo "Error: '$format' is not a valid image file extension."
    exit 1
fi

# Validate destination directory
directory=$(dirname "$path")

if ! [ -d "$directory" ]; then

    parent_directory=$(dirname "$directory")

    if [ -d "$parent_directory" ]; then
        mkdir "$directory"
    else
        echo "Error: directory \"$directory\" does not exist."
        exit 1
    fi

fi

# Validate delay
if ! [[ "$delay" =~ ^[0-9]+$ ]]; then
    echo "Delay $delay is not valid."
    exit 1
fi

# Create import command
if [ "$source" == "selection" ]; then
    cmd="magick import"
elif [ "$source" == "window" ]; then
    cmd="magick import -window \"$(xdotool getwindowfocus)\""
elif [ "$source" == "fullscreen" ]; then
    cmd="magick import -window root"
fi

# Add delay to import command
if [ "$delay" != "0" ]; then
    cmd+=" -pause $delay"
fi

# Add path to import command
cmd+=" \"$path\""

# Execute import command
eval $cmd

# Put screenshot image in clipboard
if [ $destination == "clipboard" ]; then
    xclip -selection clipboard -t image/png -i "$path"
fi

# Display screenshot preview
if [ $view_image == true ]; then

    if [ "$source" == "fullscreen" ]; then
        magick display -title "Screenshot: $filename" -resize $VIEW_SIZE% "$path"
    else
        magick display -title "Screenshot: $filename" "$path"
    fi

else

    # Set notification icon to image or icon
    if [ $IMAGE_IN_NOTIFICATION == true ]; then
        icon="file:///$path"
    else
        icon="screenshot"
    fi

    # Send screenshot notification
    if [ $destination == "clipboard" ]; then
        notify-send -i "$icon" "Screenshot" "Saved to clipboard."
    else
        notify-send -i "$icon" "Screenshot" "$path"
    fi

fi

# Remove unwanted image file
if [ $destination == "clipboard" ]; then
    rm "$path"
fi
