#!/bin/bash

# Dependencies: imagemagick, xclip, xrandr, bc
# copy = copy image to clipboard
# save = save image to file
# view = show image preview on creation
# select = grab selected rectangle
# window = grab focused window

FILETYPE="png"
PREVIEW_SIZE=60
SAVE_DIRECTORY="/home/user/images/shot"

# Parse command line arguments
for arg in "$@"; do
    case $arg in
      "--copy"|"-c") copy=true ;;
      "--save"|"-s") save=true ;;
      "--view"|"-v") view=true ;;
      "--select"|"-sel") select=true ;;
      "--window"|"-w") window=true ;;
    esac
done

# Set image file path
if [ $save ] || [ $view ]; then

    filename="$(date "+%Y-%m-%d_%H:%M:%S").$FILETYPE"
    filepath="$SAVE_DIRECTORY/$filename"

    if [ -f $filepath ]; then
        filename="$(date "+%Y-%m-%d_%H:%M:%S.%N").$FILETYPE"
        filepath="$SAVE_DIRECTORY/$filename"
    fi

fi

# Compile imagemagick command
if [ $select ]; then
    cmd="import"
elif [ $window ]; then
    cmd="import -window \"$(xdotool getwindowfocus)\""
else
    cmd="import -window root"
fi

if [ $save ] || [ $view ]; then
    cmd+=" \"$filepath\""
fi

if [ $copy ]; then
    if [ $save ] || [ $view ]; then
        cmd+=" | xclip -selection clipboard -t image/png"
    else
        cmd+=" png:- | xclip -selection clipboard -t image/png"
    fi
fi

# Run imagemagick command
eval $cmd

# View screenshot
if [ $view ]; then

    if [ "$(which sxiv | grep -i -v 'not found' | wc -l)" == "1" ]; then

        preview_size_as_float=$(echo "$PREVIEW_SIZE / 100" | bc -l)

        screen_dimensions=$(xrandr --current | grep '*' | uniq | awk '{print $1}')
        screen_width="$(cut -d 'x' -f1 <<< "$screen_dimensions")"
        screen_height="$(cut -d 'x' -f2 <<< "$screen_dimensions")"

        image_dimensions="$(identify "$filepath" | cut -d' ' -f3)"
        image_width="$(cut -d 'x' -f1 <<< "$image_dimensions")"
        image_height="$(cut -d 'x' -f2 <<< "$image_dimensions")"

        window_width=$(printf "%.0f" $(bc -l <<< "$screen_width * $preview_size_as_float"))
        window_height=$(printf "%.0f" $(bc -l <<< "($screen_height * $preview_size_as_float) + 15"))

        if [ $image_width -lt $window_width ]; then
            window_width=$image_width
            window_height=$image_height
        fi

        window_xpos=$(($((1920 - window_width)) / 2))
        window_ypos=$(($((1080 - window_height)) / 2))

        geometry="${window_width}x${window_height}+${window_xpos}+${window_ypos}"

        sxiv -g "$geometry" "$filepath"

    else

        display -resize $PREVIEW_SIZE% "$filepath"

    fi

fi

# Remove image file if save flag is not true
if [ ! $save ] && [ -f "$filepath" ]; then
    rm "$filepath"
fi
